import { NavBar } from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import 'toastr/build/toastr.css'
import { SSRProvider } from 'react-bootstrap'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'JB Motos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <SSRProvider>
          <NavBar />
          <div className='div-principal'>
            {children}
          </div>
        </SSRProvider>
      </body>
    </html>
  )
}
